### ISSUE TITLE
Dissolving multiple images

### ISSUE THREAD

**Issue by gnowakpoloniex** [wix/kampos#14]
Hi there,

Love the library. The dissolve transition is such 🔥 🔥  so seriously thank you.  My only issue is I can't find a good way to build a slideshow with this? how would I go about creating say 5 images that I could dissolve from one to the next in a loop.  This seems to be built to dissolve with a from/to.

I'm trying to build off the work here: https://css-tricks.com/nailing-that-cool-dissolve-transition/ which uses this library

Would appreciate any pointers. thank you

**Comment by ydaniv** [comment]
hey @gnowakpoloniex, thanks so much for the kind words! 😻 

I'll gladly wrap up a demo for you ASAP!

It really is a breeze, and would also be a great addition to the demos site (:

**Comment by gnowakpoloniex** [comment]
@ydaniv awesome man! can't wait to see this

**Comment by ydaniv** [comment]
Here you go: https://wix.github.io/kampos/demo/
It's just a simple demo to wrap your head around the basics.
HTH!

**Comment by gnowakpoloniex** [comment]
@ydaniv wow, thanks man! appreciate how fast you did that for me!

**Comment by ydaniv** [comment]
wOOt, closing. Feel free to comment/reopen if not clear.

**Comment by ydaniv** [comment]
oh, and @gnowakpoloniex do show us here what you did with it! 🚀 👨‍🎤 🧙‍♂️
